# Generated by Django 5.0.6 on 2024-06-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=5)),
                ('loot', models.CharField(default='Common item', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('assassin', 'Assassin'), ('warrior', 'Warrior'), ('wizard', 'Wizard'), ('knight', 'Knight'), ('archer', 'Archer')], max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=10)),
                ('experience', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('inventory', models.ManyToManyField(blank=True, to='gaming.item')),
            ],
        ),
    ]
