# Generated by Django 5.0.6 on 2024-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profession',
        ),
        migrations.AddField(
            model_name='player',
            name='classe',
            field=models.CharField(choices=[('assassin', 'Assassin'), ('warrior', 'Warrior'), ('wizard', 'Wizard'), ('knight', 'Knight'), ('archer', 'Archer')], default='archer', max_length=100),
            preserve_default=False,
        ),
    ]
